// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

// log_lik_rcpp
Rcpp::List log_lik_rcpp(arma::vec y, const arma::mat X, const arma::mat Z, const arma::vec beta, const double sigma, const arma::vec lambda, const arma::uvec lam_idx, const uint diffs);
RcppExport SEXP _lmmstest_log_lik_rcpp(SEXP ySEXP, SEXP XSEXP, SEXP ZSEXP, SEXP betaSEXP, SEXP sigmaSEXP, SEXP lambdaSEXP, SEXP lam_idxSEXP, SEXP diffsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::vec >::type y(ySEXP);
    Rcpp::traits::input_parameter< const arma::mat >::type X(XSEXP);
    Rcpp::traits::input_parameter< const arma::mat >::type Z(ZSEXP);
    Rcpp::traits::input_parameter< const arma::vec >::type beta(betaSEXP);
    Rcpp::traits::input_parameter< const double >::type sigma(sigmaSEXP);
    Rcpp::traits::input_parameter< const arma::vec >::type lambda(lambdaSEXP);
    Rcpp::traits::input_parameter< const arma::uvec >::type lam_idx(lam_idxSEXP);
    Rcpp::traits::input_parameter< const uint >::type diffs(diffsSEXP);
    rcpp_result_gen = Rcpp::wrap(log_lik_rcpp(y, X, Z, beta, sigma, lambda, lam_idx, diffs));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_lmmstest_log_lik_rcpp", (DL_FUNC) &_lmmstest_log_lik_rcpp, 8},
    {NULL, NULL, 0}
};

RcppExport void R_init_lmmstest(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
