# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

loglik_rcpp <- function(y, X, Z, beta, sigma, lambda, id, diffs) {
    .Call(`_lmmSTest_loglik_rcpp`, y, X, Z, beta, sigma, lambda, id, diffs)
}

